from __future__ import annotations


def release_status() -> dict[str, object]:
    return {
        "schema": "armctrl.release_status.v1",
        "version": "0.6.0-rc.25",
        "branch": "codex/armctrl-clean-rebuild",
        "release_readiness": "simulation_safety_preview_nonhardware_verified",
        "milestones": [
            {
                "id": "v0.2.0",
                "name": "governance-and-safety-boundary",
                "status": "contract_complete",
            },
            {
                "id": "v0.3.0",
                "name": "offline-sysid-loop",
                "status": "contract_complete_hardware_pending",
            },
            {
                "id": "v0.4.0",
                "name": "conservative-online-identification",
                "status": "contract_complete",
            },
            {
                "id": "v0.5.0",
                "name": "agent-recipe-and-cli-skill",
                "status": "contract_complete",
            },
            {
                "id": "v0.6.0-rc.25",
                "name": "simulation-safety-preview-gate-and-lerobot-eef-bridge",
                "status": "rc_nonhardware_verified_remote_backend_pending",
            },
        ],
        "hardware_pending": [
            "real_sdk_runner_hardware_validation",
            "native_lerobot_record_on_target_linux",
            "native_lerobot_rollout_on_target_linux",
            "sdk_preflight_on_target_linux",
            "sdk_handshake_plan_on_target_linux",
            "sdk_gravity_smoke_on_target_linux",
            "hold_damping_ctrl_c_hardware_landing",
            "n100d_pinocchio_figaroh_validation",
            "n100d_mujoco_moveit_pinocchio_coal_doctor",
            "hardware_ab_control_benefit_test",
        ],
        "verification": {
            "local_commands": [
                "uv sync --extra dev --extra sim",
                "uv run pytest -q",
                "uv run python -m compileall src tests",
                "uv run armctrl release status --json",
                "uv run armctrl sim doctor --json",
                "uv run armctrl agent-flow doctor --json",
                "uv sync --extra dev --extra eef",
                "uv run armctrl recipe plan home --output runs/recipe-preview-smoke --json",
                "uv run armctrl recipe export-eef-seed --plan-dir runs/recipe-preview-smoke --json",
                "uv run armctrl recipe export-agent-preset-contract --plan-dir runs/recipe-preview-smoke --json",
                "uv run armctrl agent-flow plan --preset home --eef-mode pose_delta --backend lerobot_rollout --delta-position 0.002 0.000 -0.003 --delta-rpy 0 0 0.02 --output runs/agent-flow-preview-smoke --json",
                "uv run armctrl agent-flow review --contract runs/agent-flow-preview-smoke/agent_flow_plan.json --json",
                "uv run python scripts/agent_cli_sim_experiment.py --output runs/agent-cli-sim-acceptance --json",
                "uv run armctrl eef plan-pose --frame eef_link --position 0.40 0.00 0.20 --rpy 0 0 0 --backend sdk_cartesian --output runs/eef-preview-smoke --json",
                "uv run armctrl eef plan-delta-pose --frame eef_link --delta-position 0.002 0.000 -0.003 --delta-rpy 0 0 0.02 --backend sdk_cartesian --output runs/eef-delta-preview-smoke --json",
                "uv run armctrl eef runtime-plan --plan-dir runs/eef-preview-smoke --model X5 --interface can0 --json",
                "uv run armctrl eef export-lerobot-action --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef export-sdk-cartesian --plan-dir runs/eef-preview-smoke --model X5 --interface can0 --json",
                "uv run armctrl eef export-moveit-servo --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef export-runtime-bridge --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef export-runner-contract --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef export-agent-runtime-contract --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef export-agent-session-plan --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef preview-runner --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef export-runner-contract --plan-dir runs/eef-preview-smoke --output runs/eef-preview-smoke/eef_runner_contract.json --json",
                "uv run armctrl eef sample-runner --runner-contract runs/eef-preview-smoke/eef_runner_contract.json --json",
                "uv run armctrl eef export-sdk-helper-plan --runner-contract runs/eef-preview-smoke/eef_runner_contract.json --json",
                "uv run python scripts/sdk_cartesian_contract_helper_sample.py --runner-contract runs/eef-preview-smoke/eef_runner_contract.json --json",
                "uv run armctrl eef export-agent-runtime-contract --plan-dir runs/eef-preview-smoke --backend lerobot_rollout --output runs/eef-preview-smoke/eef_agent_runtime_contract.json --json",
                "uv run armctrl lerobot agent-runtime-helper-plan --agent-runtime-contract runs/eef-preview-smoke/eef_agent_runtime_contract.json --json",
                "uv run python scripts/lerobot_agent_runtime_helper_sample.py --agent-runtime-contract runs/eef-preview-smoke/eef_agent_runtime_contract.json --json",
                "uv run armctrl lerobot export-processor-contract --eef-plan-dir runs/eef-preview-smoke --output runs/eef-preview-smoke/lerobot_processor_contract.json --json",
                "uv run armctrl lerobot processor-helper-preview --processor-contract runs/eef-preview-smoke/lerobot_processor_contract.json --urdf-path configs/models/X5_camera.urdf --safe-config configs/x5.safe.yaml --json",
                "uv run python scripts/lerobot_processor_contract_helper_sample.py --processor-contract runs/eef-preview-smoke/lerobot_processor_contract.json --urdf-path configs/models/X5_camera.urdf --safe-config configs/x5.safe.yaml --json",
                "uv run armctrl eef plan-pose --frame eef_link --position 0.40 0.00 0.20 --rpy 0 0 0 --backend moveit_servo --output runs/eef-moveit-helper-smoke --json",
                "uv run armctrl eef export-runner-contract --plan-dir runs/eef-moveit-helper-smoke --output runs/eef-moveit-helper-smoke/eef_runner_contract.json --json",
                "uv run armctrl eef export-moveit-helper-plan --runner-contract runs/eef-moveit-helper-smoke/eef_runner_contract.json --json",
                "uv run python scripts/moveit_servo_contract_helper_sample.py --runner-contract runs/eef-moveit-helper-smoke/eef_runner_contract.json --json",
                "uv run armctrl eef synthesize-preview --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl eef synthesize-preview --plan-dir runs/eef-delta-preview-smoke --json",
                "uv run armctrl eef stage-trajectory --plan-dir runs/eef-preview-smoke --trajectory runs/eef-preview-smoke/backend_joint_trajectory.csv --json",
                "uv run armctrl lerobot config-plan rollout --model X5 --robot-interface can0 --policy-path outputs/train/act_arx5/checkpoints/last/pretrained_model --eef-plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl lerobot export-processor-contract --eef-plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl lerobot preview-rollout --eef-plan-dir runs/eef-preview-smoke --urdf-path configs/models/X5_camera.urdf --safe-config configs/x5.safe.yaml --json",
                "uv run armctrl lerobot stage-rollout-trajectory --eef-plan-dir runs/eef-preview-smoke --trajectory runs/eef-preview-smoke/backend_joint_trajectory.csv --json",
                "uv run armctrl lerobot review-rollout --eef-plan-dir runs/eef-preview-smoke --trajectory runs/eef-preview-smoke/backend_joint_trajectory.csv --urdf-path configs/models/X5_camera.urdf --safe-config configs/x5.safe.yaml --json",
                "uv run armctrl eef review --plan-dir runs/eef-preview-smoke --json",
                "uv run armctrl sysid plan gravity_sweep --dof 6 --sample-hz 100 --duration 2 --amplitude 0.05 --q-center 0 0.30 0.30 0 0 0 --urdf-path configs/models/X5_camera.urdf --safe-config configs/x5.safe.yaml --output runs/plan-preview-smoke --json",
                "uv sync --extra dev --extra lerobot",
                "uv run armctrl lerobot doctor --model X5 --robot-interface can0 --teleop-interface can1 --json",
                "uv run armctrl sysid run gravity_sweep --adapter sdk --duration 8 --amplitude 0.5 --q-center 0 0.30 0.30 0 0 0 --output runs/tmp-confirm-check --confirm 'I UNDERSTAND THIS WILL MOVE THE ARM' --json",
            ],
            "test_count": 190,
            "scope": "local contracts and non-hardware simulation safety gates through v0.6.0-rc.25",
        },
        "deferred_validation": {
            "requires_hardware": [
                "real_sdk_runner_hardware_validation",
                "native_lerobot_record_on_target_linux",
                "native_lerobot_rollout_on_target_linux",
                "sdk_preflight_on_target_linux",
                "sdk_handshake_plan_on_target_linux",
                "sdk_gravity_smoke_on_target_linux",
                "hold_damping_ctrl_c_hardware_landing",
                "hardware_ab_control_benefit_test",
            ],
            "requires_external_tool": [
                "n100d_pinocchio_figaroh_validation",
                "n100d_mujoco_moveit_pinocchio_coal_doctor",
            ],
            "requires_geometry_upgrade": [],
        },
        "notes": [
            "Recipe plans are dry-run previews with machine-readable risk explanations.",
            "Recipe execution remains rejected until a verified hardware backend exists.",
            "armctrl now also has a thin agent-flow orchestration surface so Agent callers can compose preset posture, bounded EEF intent, runtime helper handoff, and shared review from one non-hardware entry point.",
            "agent-flow now also has doctor and review surfaces so Agent callers can inspect the top-level non-hardware motion entrypoint and replay its durable contract without reconstructing lower-level review chains.",
            "armctrl-agent-motion now defines a compact Agent Action Protocol so Agent callers classify motion as preset.apply, eef.pose_delta, eef.pose_absolute, eef.twist, or rollout.prepare before selecting CLI commands.",
            "The repo now also carries a fixed Agent CLI simulation experiment that replays off-center EEF preview, recenter, visibly large EEF control, LeRobot processor preview, and shared review through public CLI commands only.",
            "Recipe plan bundles can now export an EEF seed so Agent flows can hand a reviewed preset posture into later bounded EEF preview work.",
            "Recipe plans now also have an agent-preset-contract export so Agent callers can consume one consolidated preset-action handoff artifact instead of stitching manifest, seed, and next steps together themselves.",
            "Agent-facing recipe preset and EEF runtime contracts now also emit ordered_steps so sequencing is machine-readable instead of implicit in next_steps prose.",
            "Recipe plan bundles now also materialize eef_seed.json as a first-class artifact instead of leaving the bridge only as an on-demand export command.",
            "recipe execute --backend sim now also returns a structured handoff and next_steps so preset-action previews can feed later EEF work without ad hoc glue.",
            "recipe plan --output and recipe execute --backend sim now also emit an agent_runtime_profile so preset-action bundles advertise a stable handoff role to Agent callers.",
            "EEF preview synthesis can now also consume a recipe plan's eef_seed.json directly so preset postures and later EEF previews share one artifact-driven handoff.",
            "EEF plan, runtime-plan, and review now form a continuous non-hardware workflow around mature backend ownership.",
            "runtime-plan can now surface backend-specific bridge previews and next-step hints for sdk_cartesian and moveit_servo plans.",
            "runtime-plan now also emits an agent_runtime_profile so EEF bundles advertise a stable runtime handoff role to Agent callers.",
            "runtime-plan also accepts an explicit backend override with plan_dir so the same bounded EEF intent can be handed to lerobot_rollout without regenerating artifacts.",
            "EEF bridge export now also has a unified backend-agnostic surface that delegates to the mature-owner-specific exporters.",
            "EEF bridge export now also has a runner-contract surface that tells backend helpers exactly which reviewed trajectory artifact to emit back into armctrl.",
            "runner-contract now also emits the same agent_runtime_profile shape as runtime-plan so Agent callers can classify EEF handoff bundles uniformly.",
            "EEF now also has an agent-runtime-contract export so Agent/helper loops can stream stable EEF action frames into mature runtime owners without losing the shared review return path.",
            "EEF now also has an agent-session-plan export so Agent callers can consume one top-level non-hardware session contract instead of manually stitching runtime contracts and backend helper plans together.",
            "The repo now also carries a LeRobot-specific agent-runtime helper sample that converts EEF Agent runtime contracts into processor-oriented rollout helper plans.",
            "The repo now also carries a LeRobot processor-contract helper sample that consumes a serialized rollout processor contract and closes into the shared preview/review chain.",
            "LeRobot now also has CLI-native helper-plan and helper-preview commands so Agent callers do not need to reach for repo-local sample scripts as their primary entry point.",
            "SDK cartesian and MoveIt Servo runner contracts now also have CLI-native helper-plan exports so Agent callers can stay on the main armctrl JSON surface for realtime EEF backend handoff planning.",
            "EEF now also has a preview-runner helper that closes the mature-backend handoff contract through the shared non-hardware simulation review chain.",
            "EEF now also has a sample-runner helper that consumes a serialized runner contract artifact and demonstrates the external-helper integration boundary end to end.",
            "The repo now also carries a thinner sdk_cartesian external-helper sample script that converts a serialized runner contract into an SDK-shaped session plan artifact.",
            "The repo now also carries a thinner moveit_servo external-helper sample script that converts a serialized runner contract into a ROS 2 MoveIt Servo session plan artifact.",
            "EEF now also has a synthesize-preview helper that produces a conservative non-hardware joint trajectory and immediately reuses the shared review/simulation chain.",
            "Pink-backed EEF preview synthesis is now an explicit optional dependency path via uv sync --extra dev --extra eef on Linux targets.",
            "EEF plans can now be exported as LeRobot-friendly cartesian action contracts for Agent and rollout-side reuse.",
            "EEF plan payloads now also expose a stable Agent-facing action vocabulary so backend-specific servo surfaces stay behind the handoff contracts.",
            "The EEF Agent vocabulary now includes pose_delta with SDK delta control and MoveIt Servo twist-handoff mappings, and the shared preview chain can validate that intent.",
            "Agent-flow and LeRobot processor contracts now also declare that the preferred LeRobot-aligned training action is eef.pose_delta while robot_action_processor and robot_observation_processor remain the adaptation owners.",
            "EEF plans can now also be exported as ARX5 SDK cartesian bridge artifacts for programmatic mature-backend integrations.",
            "EEF plans can now be exported as MoveIt Servo bridge artifacts around standard ROS TwistStamped or PoseStamped contracts.",
            "EEF backend trajectories can now be staged into the conventional review path before shared simulation approval.",
            "LeRobot rollout trajectories can now be staged through the same shared review-path contract.",
            "LeRobot rollout planning now surfaces runtime-owner and next-step hints so Agent flows do not need to reconstruct the rollout handoff manually.",
            "LeRobot rollout planning also exposes a processor-bridge contract for programmatic robot_action_processor and robot_observation_processor integrations around the exported EEF action vocabulary.",
            "LeRobot now also has a dedicated export-processor-contract surface so Agent/runtime helpers can consume one explicit EEF-to-rollout handoff artifact.",
            "LeRobot processor contracts and helper samples now also emit ordered_steps so export, preview, staging, and review dependencies are machine-readable for Agent callers.",
            "LeRobot rollout review now reuses the shared EEF simulation gate instead of introducing a separate validation path.",
            "LeRobot rollout preview now gives Agent flows a thin non-hardware closure path from exported EEF action semantics to a reviewed joint trajectory preview.",
            "LeRobot record/train/rollout remain native LeRobot commands; armctrl emits plans and metadata only.",
            "Install LeRobot integrations with uv sync --extra dev --extra lerobot on Linux targets.",
            "Parameter packages require package-gated solver evidence before rollout.",
            "Install MuJoCo preview support with uv sync --extra dev --extra sim on Linux targets.",
            "MoveIt 2 on ROS 2 hosts must be sourced before Python module detection, for example source /opt/ros/jazzy/setup.bash.",
            "X5_camera.urdf now has project-local STL assets so Pinocchio/coal can load native geometry without SDK wheel paths.",
            "Known adjacent X5 assembly mesh overlaps are configured as named allowed collision pairs; every other Pinocchio/coal collision remains a hard gate.",
            "MuJoCo preview now performs a qpos trajectory rollout with mj_forward and reports contact counts instead of only loading the URDF.",
            "MuJoCo rollout reuses the named allowed collision pairs; unlisted contacts still fail the safety gate.",
            "sim preview and sysid plan can render SVG trajectory previews, including unsafe warning annotations.",
            "sim preview can render browser-openable HTML URDF trajectory animations; unsafe trajectories still render with WARNING and gate reasons.",
            "The SDK sysid runner is wired for low-amplitude smoke collection, but hardware validation is still explicit deferred validation.",
            "SysID plans reject trajectories whose adjacent joint samples exceed max_joint_step_rad before any SDK backend is instantiated.",
            "SysID plans now write trajectory_preview.json and gate motion through the simulation safety preview before SDK execution.",
        ],
    }


def release_notes() -> dict[str, object]:
    status = release_status()
    included = [
        "governance and safety boundary",
        "offline SysID loop contracts",
        "conservative online identification policy",
        "Agent recipe CLI skill",
        "Top-level agent-flow doctor and durable review replay surfaces",
        "Agent Action Protocol and CLI skill usage manual for preset, EEF, and LeRobot rollout-preparation intents",
        "Fixed Agent CLI simulation experiment for off-center EEF preview, recenter, large EEF control, and LeRobot processor preview",
        "Recipe-to-EEF seed handoff for reviewed preset postures",
        "Recipe preset contract export for Agent-facing handoff",
        "EEF plan, runtime-plan, and shared simulation review contracts",
        "Agent-facing EEF action vocabulary for pose, pose_delta, and twist plans",
        "Top-level Agent session-plan export for realtime EEF loops",
        "Machine-readable Agent-to-LeRobot EEF compatibility contract with pose_delta as the preferred training action",
        "LeRobot-friendly EEF action export for Agent/runtime bridge",
        "ARX5 SDK cartesian bridge export for EEF plans",
        "MoveIt Servo bridge export for twist-style and pose-style EEF plans",
        "Unified runtime bridge export for EEF plans",
        "Runner contract export for EEF backend helpers",
        "Agent runtime contract export for streaming EEF action frames into mature backends",
        "LeRobot agent runtime helper sample for EEF action streams",
        "LeRobot processor contract helper sample for rollout preview closure",
        "CLI-native LeRobot helper-plan and helper-preview commands for Agent callers",
        "Runner preview helper for non-hardware mature-backend closure",
        "Sample runner helper that consumes serialized runner-contract artifacts",
        "CLI-native SDK and MoveIt helper-plan commands for Agent callers",
        "SDK cartesian helper sample script for external runtime integration",
        "MoveIt Servo helper sample script for external runtime integration",
        "EEF synthesize-preview helper for non-hardware joint preview closure",
        "Optional Pink dependency path for Linux EEF preview synthesis",
        "EEF backend trajectory staging into the shared review path",
        "LeRobot processor contract export for EEF runtime helpers",
        "Ordered-step sequencing metadata for LeRobot processor and helper contracts",
        "LeRobot rollout trajectory staging on the shared review path",
        "LeRobot rollout review on the shared simulation gate",
        "LeRobot rollout preview helper for non-hardware EEF-to-rollout closure",
        "LeRobot doctor, native command plans, and dataset metadata bridge",
        "SDK gravity smoke runner with confirmation, safety gates, and damping landing path",
        "Safety-space config plus simulation doctor and SysID trajectory preview gate",
    ]
    deferred = list(status["hardware_pending"])
    title = "armctrl 0.6.0-rc.25 simulation safety preview"
    summary = (
        "simulation_safety_preview_nonhardware_verified: safety-space config, "
        "simulation backend doctor, top-level agent-flow doctor/review, recipe preview, EEF runtime planning, EEF backend trajectory staging, EEF runner preview, EEF sample runner, sdk_cartesian helper sample, moveit servo helper sample, LeRobot rollout trajectory staging, LeRobot rollout preview, LeRobot-friendly EEF export, ARX5 SDK cartesian bridge export, MoveIt Servo bridge export, LeRobot rollout review, and SysID trajectory preview gates are present; "
        "real robot movement and target-host mature backend validation remain deferred."
    )
    markdown = (
        f"# {title}\n\n"
        f"{summary}\n\n"
        "## Included\n"
        + "\n".join(f"- {item}" for item in included)
        + "\n\n## Deferred Validation\n"
        + "\n".join(f"- {item}" for item in deferred)
        + "\n"
    )
    return {
        "schema": "armctrl.release_notes.v1",
        "version": status["version"],
        "title": title,
        "summary": summary,
        "sections": {
            "included": included,
            "deferred": deferred,
        },
        "markdown": markdown,
    }
